apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: front-envoy-deployment
  namespace: front-envoy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front-envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:latest    
        ports:
          - containerPort: 9901
            protocol: TCP
            name: envoy-admin
          - containerPort: 80
            protocol: TCP
            name: front-http
        volumeMounts:
          - name: envoy-config-volume
            mountPath: /etc/envoy-config/
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/config.yaml", "--v2-config-only", "-l", "trace","--service-cluster","cluster","--service-node","node"]
      volumes:
        - name: envoy-config-volume
          configMap:
            name: envoy-config
            items:
              - key: config
                path: config.yaml
      imagePullSecrets:
      - name: regsecret

---

kind: Service
apiVersion: v1
metadata:
  name: front-envoy
  namespace: front-envoy
spec:
  ports:
  - name: promo-svc-port
    port: 80
    targetPort: front-http
  selector:
    app: front-envoy
  type: LoadBalancer